# Hardcoded API keys (replace with your real keys for local dev)

GOOGLE_GENERATIVE_AI_API_KEY = "YOUR_GEMINI_OR_GENERATIVE_AI_KEY_HERE"
GOOGLE_CLOUD_TTS_API_KEY = "YOUR_GOOGLE_CLOUD_TTS_API_KEY_HERE"
